baseURL: //marcelocantos.com
languageCode: en-us
title: Marcelo Cantos
theme: vanilla-bootstrap-hugo-theme
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsStyle: github

menu:
  main:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Blog
    pre: edit
    url: /posts/
    weight: 2
  - name: RSS
    pre: rss
    url: /index.xml
    weight: 5
