baseURL = "http://example.org/"
languageCode = "en-us"
title = "Marcelo Cantos"
theme = "vanilla-bootstrap-hugo-theme"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "RSS"
    pre = "rss"
    url = "/index.xml"
    weight = 5
